# Generated by Django 5.1.1 on 2024-11-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_rol_delete_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='fk_id_rol',
        ),
    ]
