# Generated by Django 5.1.1 on 2024-12-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='estado',
            field=models.CharField(choices=[('Prestado', 'Prestado'), ('Disponible', 'Disponible'), ('En reparación', 'En reparación')], max_length=50, null=True),
        ),
    ]
