# Generated by Django 5.1.1 on 2024-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0003_alter_herramientas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='estado',
            field=models.CharField(choices=[('Prestado', 'Prestado'), ('En reparación', 'En reparación'), ('Disponible', 'Disponible')], max_length=50, null=True),
        ),
    ]
