# Generated by Django 5.1.1 on 2025-02-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0004_alter_herramientas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='estado',
            field=models.CharField(choices=[('En reparación', 'En reparación'), ('Prestado', 'Prestado'), ('Disponible', 'Disponible')], max_length=50, null=True),
        ),
    ]
